name: Deploy the auth function
on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            APP_NAME: staticfaq
            RESOURCE_GROUP: Delivery_Resources
            FUNCTION_NAME: static-web-auth-function
            FUNCTION_ID: "/subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/${RESOURCE_GROUPS}/providers/Microsoft.Web/sites/${FUNCTION_NAME}"
            TF_VAR_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
            TF_VAR_GITHUB_SECRET_ID: ${{ secrets.OAUTH_CLIENT_SECRET }}
        steps:
        - uses: actions/checkout@v3
        - name: Initialise Terraform
          run: terraform init
          working-directory: infrastructure
        - name: Create the infrastructure
          run: terraform apply -auto-approve
          working-directory: infrastructure
        - name: Install static web app CLI
          run: npm install -g @azure/static-web-apps-cli
        - name: Build the HTML
          run: docker compose up build_html
        - name: Deploy the webapp itself
          run: swa deploy .\html_output\ -n $APP_NAME -R $RESOURCE_GROUP --env production
        #   working-directory: code
        - name: Link the webapp to the auth function
          run: |
            az staticwebapp backends link \
            -n $APP_NAME
            --resource-group $RESOURCE_GROUP
            --backend-resource-id $FUNCTION_ID
            --backend-region "Uk South"
